---
title: "HW 08 Part 1"
author: "Melvin Cummings"
date: "`r format(Sys.time(), '%d %B %Y')`"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---

```{r}
library(tidyverse)
library(lubridate)

```

##Question 1
```{r}
birth_date <- "3 July 1996"

# Elizabeth Garret Anderson was the first female physician

anderson <- "9 June 1836"

# Mary Anning discovered the first complete Plesiosaur fossil, and other important Jurassic fossils

anning <- "1799/05/21"

# Alice Augusta Ball was a chemist who developed the first injectable treatment for leprosy.

ball <- "July 24, 1892"

# Sylvia Earle was the first chieft scientist at NOAA

earle <- "August, 30 (1935)"

# Rosalind Franklin used x-ray diffraction to discover DNA structure. Watson and Crick claimed credit.

franklin <- "25th of July, 1920"

# Ester Lederberg was the first to discover that viruses infect bacteria. Led to discovery of lambda bacteriophage

lederberg <- "December 18, 1922"

# Barbara McClintock discovered transposable elements (jumping genes), and developed staining techniques to study chromosomes

mcclintock <- "16061902"

# Martin Luther King's birthday is coming up. Let's remember a dream

mlk_birth <- "1/15/29"

mlk_dream <- "1963 August 08"

```

```{r}
melvin <- dmy(birth_date)

anderson <- dmy(anderson)

anning <- ymd(anning)

ball <- mdy(ball)

earle <- mdy(earle)

franklin <- dmy(franklin)

lederberg <- mdy(lederberg)

mcclintock <- dmy(mcclintock)

mlk_birth <- mdy(mlk_birth)

mlk_dream <- ymd(mlk_dream)

melvin
anderson
anning
ball
earle
franklin
lederberg
mcclintock
mlk_birth
mlk_dream




```

##Question 2

MLK birth year is incorrect

```{r}
mlk_birth <- update(mlk_birth, year = 1929)
mlk_birth
```

##Question 3

```{r}
melvin_weekday <- wday(melvin, label = TRUE, abbr = FALSE)
melvin_weekday
```
I was born on wednesday.

##Question 4

```{r}
melvin_weekday <- update(melvin, year = 2019)
melvin_weekday <- wday(melvin_weekday, label = TRUE, abbr = FALSE)
melvin_weekday
```

##Question 5

```{r}
melvin_2525 <- update(melvin, year = 2525)
melvin_2525_weekday <- wday(melvin_2525, label = TRUE, abbr = TRUE)
melvin_2525_weekday
```

```{r}
age = year(melvin_2525) - year(melvin)
age
```

##Question 6

```{r}
days <- abs(anderson - ball)
days
```

##Question 7

```{r}
mlk_days <- abs(mlk_birth - mlk_dream)
mlk_days
```



```{r}
birth_date1 <- c("1996-07-03", "1836-06-09", "1799-05-21", "1892-07-24", "1935-08-30", "1920-07-25", "1922-12-18", "1902-06-16", "1929-01-15")
names(birth_date1) <- c("melvin", "anderson", "anning", "ball", "earle", "franklin", "lederberg", "mcclintock", "mlk_birth")
birth_date1
```

```{r}
years <- year(birth_date1)
leap_year <- leap_year(years)
leap_year <- years[leap_year]
leap_year
```

Anderson, ball, franklin, and me were born in leap years

```{r}
birth_date2 <- ymd(birth_date1)
birthdays <- birth_date2[1]
birthday_diff <- melvin - birth_date2
names(birthday_diff) <- c("melvin", "anderson", "anning", "ball", "earle", "franklin", "lederberg", "mcclintock", "mlk")
sort(birthday_diff, decreasing = TRUE)
```

#Part 2

```{r}
file_path <- "~/Bi485/cummings_melvin/data"

lake_ice <- read_csv(file.path(file_path, "lake_ice.csv"))
lake_ice
```

```{r}
lake_ice1 <- filter(lake_ice, lakename == "LAKE MENDOTA")
lake_ice1
```

```{r}
lake_ice1 <- select(lake_ice1, iceon_year, iceon_month, iceon_day, iceoff_year, iceoff_month, iceoff_day)
lake_ice1
```

```{r}
lake_ice2 <- lake_ice1 %>% 
  select(iceon_year, iceon_month, iceon_day, iceoff_year, iceoff_month, iceoff_day) %>% 
  mutate(ice_on = make_date(iceon_year,iceon_month, iceon_day),
         ice_off = make_date(iceoff_year, iceoff_month, iceoff_day))
lake_ice2

```

```{r}
lake_ice3 <- lake_ice2 %>% 
  mutate(duration = as.numeric(ice_off - ice_on))
lake_ice3
```

```{r}
ggplot(data = lake_ice3) +
  geom_line(mapping = aes(x = iceoff_year, y = duration), na.rm = TRUE) +
  coord_cartesian(xlim = c(1850, 2013)) +
  xlab("Year") + ylab("Ice Duration (days)")
```

##Soil 

```{r}
file_path2 <- "~/Bi485/cummings_melvin/data"

soil <- read.delim(file.path(file_path2, "soil_co2.txt"))
soil
```

```{r}
january <- make_date(year = 2006, day = 1, month = 1)
january
```

```{r}
soil1 <- soil %>% 
  rename(Day_number = DayN..) %>% 
  rename(Day = Datecode..) %>% 
  rename(Minute = Min..) %>% 
  rename(Vegetation_sample = Veg..) %>% 
  rename(Plot = Plot..) %>% 
  rename(Group = Group..) %>%
  rename(CO2_concentration = CorrCO2..) %>%
  rename(Soil_type = SoilT..)
soil1
```


```{r}
soil2 <- soil %>% 
  mutate(Date = january + DayN..,
         Year = year(Date),
         Month = month(Date, label = TRUE, abbr = TRUE)) %>% 
group_by(Year, Month)
soil2
```


```{r}
soil3 <- soil2 %>%
  summarise(
    mean_CO2 = mean(CorrCO2..),
    se_Co2 = sd(CorrCO2..)/sqrt(n())
  )
soil3
```

```{r}
ggplot(data = soil3) +
  geom_col(aes(x = Month, y = mean_CO2)) +
  geom_linerange(aes(x = Month, ymin = mean_CO2 - se_Co2, ymax = mean_CO2 + se_Co2)) +
  facet_wrap(~ Year, ncol = 3)
```

```{r}
ggplot(data = soil3) +
  geom_point(aes(x = Month, y = mean_CO2)) +
  geom_linerange(aes(x = Month, ymin = mean_CO2 - se_Co2, ymax = mean_CO2 + se_Co2)) +
  facet_wrap(~Year, nrow = 2)
```


```{r}
file_path3 <- "~/Bi485/cummings_melvin/data"

thebes <- read_csv(file.path(file_path3, "thebes_discharge.csv"))
thebes
```

```{r}
thebes
colnames(thebes)
thebes2 <- thebes %>%
  gather ("1988":"2018", key = "Year", value = "discharge") %>% 
  group_by(Year, Month) %>% 
  mutate(discharge = discharge / 1000,
         Event = case_when(
           Year== "1993" ~ "Flood",
           Year == "2011" ~ "Flood",
           Year == "1988" ~ "Drought",
           Year == "2012" ~ "Drought",
           TRUE ~ "Normal"),
         average_discharge = mean(discharge), na.rm = FALSE)
thebes2
```

```{r}
eventyear <- thebes2 %>% 
  filter(Event %in% c ("Floot", "Drought"))
eventyear
```

```{r}
plot <- thebes2 %>% 
  ggplot() +
  geom_line(aes(x = Month, y = average_discharge, group = Year),
            color = "gray70",
            size = 0.3) + 
  labs(x=NULL, y ="Discharge (cf/s, thousand)")
plot
```

```{r}
plot2 <- thebes2 %>% 
  ggplot() +
  geom_line(aes(x = Month, y = average_discharge, group = Year),
            color = "gray70",
            size = 0.3) + 
  labs(x=NULL, y ="Discharge (cf/s, thousand)") +
  geom_line(Data = years, aes(x= Month, y = average_discharge, group = Year, color = Event))
plot2
```









